### ISSUE TITLE
Resolve _requestPreprocessor() Typescript error

### ISSUE THREAD

**Issue by SteveAtSentosa** [sentosatech/stcland#1]
If you remove `// @ts-expect-error because TS is a pain in the ass` a typescript error will be reported.  Please resolve this error.

![Image](https://github.com/SteveAtSentosa/stcland/assets/5873306/eef27913-dea2-4635-8111-deb69e13cf55)

```ts
const _requestPreprocessor =
  (opts: _RequestPreprocessorOptions) =>
  (req: AxiosRequestConfig): AxiosRequestConfig =>
{
  const { verbose, getAccessToken } = opts
  const accessToken = getAccessToken()
  const { method, baseURL, url, data } = req

  if (verbose) {
    console.debug(`\n${method} (new) ${baseURL}${url}`)
    if (data) console.debug('body', data)
  }

  return accessToken
    ? assocPath(['headers', 'Authorization'], `Bearer ${accessToken}`, req)
    : req
}
```

**Comment by chjuruena** [comment]
I changed the argument of type from AxiosRequestConfig to  InternalAxiosRequestConfig. And also updated the axios imports.

So far that removed the typscript eslint error. 

Lines 102 - 104.
```
const _requestPreprocessor =
  (opts: _RequestPreprocessorOptions) =>
  (req: InternalAxiosRequestConfig<unknown>):  InternalAxiosRequestConfig<unknown> =>

```

Is this acceptable solution?

**Comment by SteveAtSentosa** [comment]
You did it !!! Nice work.

Do you know how to create a merge request?  If not, you can work with Bex, and we will get your first fix merged :)
